import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { Access, Categories, Characteristic, Formats, Perms, Service, Units } from '@homebridge/hap-nodejs'

const __dirname = dirname(fileURLToPath(import.meta.url))

// @ts-expect-error - TS7016
const { EveHomeKitTypes } = await import('homebridge-lib/EveHomeKitTypes')
// @ts-expect-error - TS7016
const { MyHomeKitTypes } = await import('homebridge-lib/MyHomeKitTypes')

const homebridge = {
  hap: {
    Access,
    Categories,
    Characteristic,
    Formats,
    Perms,
    Service,
    Units,
  },
}

const customTypes = [
  new EveHomeKitTypes(homebridge),
  new MyHomeKitTypes(homebridge),
]

/** Generate Service Types */

let Services = [
  'export const Services = {',
] as any

const serviceUUIDs = new Set()
const serviceNames = new Set()
const serviceEntries = [
  ...Object.entries(Service),
  ...customTypes.flatMap(customType => Object.entries(customType.Services)),
]

for (const [name, value] of serviceEntries) {
  if (value.UUID) {
    if (!serviceUUIDs.has(value.UUID)) {
      Services.push(`  '${value.UUID}': '${name}',`)
      serviceUUIDs.add(value.UUID)
    }
    if (!serviceNames.has(name)) {
      Services.push(`  '${name}': '${value.UUID}',`)
      serviceNames.add(name)
    }
  }
}

Services.push(`}\n\n`)
Services = Services.join('\n')

/** Generate Characteristic Types */

let Characteristics = [
  'export const Characteristics = {',
] as any

const characteristicEntries = [
  ...Object.entries(Characteristic),
  ...customTypes.flatMap(customType => Object.entries(customType.Characteristics)),
]

const characteristicUUIDs = new Set()
const characteristicNames = new Set()

for (const [name, value] of characteristicEntries) {
  if (value.UUID) {
    if (!characteristicUUIDs.has(value.UUID)) {
      Characteristics.push(`  '${value.UUID}': '${name}',`)
      characteristicUUIDs.add(value.UUID)
    }
    if (!characteristicNames.has(name)) {
      Characteristics.push(`  '${name}': '${value.UUID}',`)
      characteristicNames.add(name)
    }
  }
}

Characteristics.push(`}\n\n`)
Characteristics = Characteristics.join('\n')

/** Generate Category Types */

let Category = [
  'export const Categories = {',
] as any

// @ts-expect-error - TS2475
for (const [name, value] of Object.entries(Categories)) {
  if (typeof value === 'number') {
    Category.push(`  ${name}: ${value},`)
  }
}

Category.push(`}\n\n`)
Category = Category.join('\n')

let Enums = [
  'export const Enums = {',
] as any

for (const [name, value] of Object.entries(Characteristic)) {
  if (typeof value === 'function' && value.prototype) {
    const staticKeys = Object.getOwnPropertyNames(value)
      .filter(
        key =>
          key !== 'length'
          && key !== 'name'
          && key !== 'prototype'
          && key !== 'UUID'
          && typeof (value as any)[key] !== 'function',
      )
    if (staticKeys.length > 0) {
      Enums.push(`  ${name}: {`)
      staticKeys.forEach((k) => {
        Enums.push(`    ${(value as any)[k]}: '${k}',`)
      })
      Enums.push('  },')
    }
  }
}
Enums.push(`}\n`)
Enums = Enums.join('\n')

const out = `/* This file is automatically generated */\n\n${Services}${Characteristics}${Category}${Enums}`

writeFileSync(resolve(__dirname, '../src/hap-types.ts'), out, 'utf8')
